[project]
name = "i18n"
version = "0.1.0"
description = "Translation services"
readme = "README.md"
authors = [
    { name = "Rafal Padkowski", email = "rafaelp@poczta.onet.pl" }
]
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
